import Head from 'next/head'
import Footer from '../src/components/Footer/Footer';
import Header from '../src/components/Header/Header';
import Lessons from '../src/components/Lessons/Lessons';

export default function Home() {
  return (
    <div>
      <Head>
        <title>kenya kitesurfing school</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <Lessons />
        <Footer />
    </div>
  )
}

