import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>kenya kitesurfing school</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      hello
    </div>
  )
}
